name: incpacientes
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  sticky_headers: "^0.1.8"
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  flutter_modular: ^1.2.5+1
  shared_preferences: ^0.5.7+3
  intl: ^0.16.1
  mask_text_input_formatter: ^1.0.6
  flutter_staggered_animations: ^0.1.2
  flutter_icons: ^1.1.0
  url_launcher: ^5.4.10
  url_launcher_web: ^0.1.1+6
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatDisplay-Black.ttf
          weight: 900

    - family: RedHatText
      fonts:
        - asset: assets/fonts/RedHatText-Regular.ttf
        - asset: assets/fonts/RedHatText-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatText-Medium.ttf
          weight: 500

  assets:
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  watch: flutter pub run build_runner watch --delete-conflicting-outputs